KT_ZG https://services.geo.zg.ch/ows/Hecken_Feldgehoelze?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Hecken_Feldgehoelze?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad775a1850>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Hist_Gewaesser?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Hist_Gewaesser?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad75d49940>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Hoehenkurven_Isobathen?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Hoehenkurven_Isobathen?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad775a10a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Jagdbezirke?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Jagdbezirke?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76aff1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Kinderbetreuung?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Kinderbetreuung?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76affa60>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Kunstbauten?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Kunstbauten?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76b10340>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Landwertzonen_Steuern?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Landwertzonen_Steuern?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76b10be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Landwirtschaft?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Landwirtschaft?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76b106a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Messstellen_an_Gewaessern?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Messstellen_an_Gewaessern?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76b102b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Moorlandschaften?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Moorlandschaften?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad75d49940>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/NGHK_Phaenomene?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/NGHK_Phaenomene?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76b0aa60>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/NGHK_Prozesse?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/NGHK_Prozesse?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad775a1130>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Naturobjekte?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Naturobjekte?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad775a1ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Naturschutz?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Naturschutz?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76af84c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Neophyten?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Neophyten?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad775a39a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Orthofotos?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Orthofotos?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76af8190>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Ortsbildschutz?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Ortsbildschutz?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad77578190>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Parkplaetze?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Parkplaetze?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad77578a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Points_of_Interest?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Points_of_Interest?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad775a1310>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Radwege?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Radwege?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad775a1b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Richtplan?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Richtplan?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76b0a460>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Schulhaeuser_Kindergaerten?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Schulhaeuser_Kindergaerten?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad775a3ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Schutzraumbau?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Schutzraumbau?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76b0a190>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Schutzwald?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Schutzwald?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad775a1e20>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Standorte_Wahlplakate?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Standorte_Wahlplakate?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad775a15b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Statische_Waldgrenzen?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Statische_Waldgrenzen?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7756f310>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Strassenlaermkataster_Gemeindestrassen?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Strassenlaermkataster_Gemeindestrassen?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7756fbb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Strassenlaermkataster_Kantonsstrassen?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Strassenlaermkataster_Kantonsstrassen?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76b10490>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Treffpunkte_RDZ?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Treffpunkte_RDZ?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7756f220>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Verkehrszaehlung?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Verkehrszaehlung?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7748ce50>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Zonenplan?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Zonenplan?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdbac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/defibrillatoren?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/defibrillatoren?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdb640>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/geologisches_aufschlussarchiv?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/geologisches_aufschlussarchiv?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdb790>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/kbs?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/kbs?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7748c100>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/pbv?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/pbv?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7748c6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/stand_der_erschliessung?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/stand_der_erschliessung?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7756fbb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Abfallsammelstellen?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Abfallsammelstellen?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad773a2cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Abstandslinien?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Abstandslinien?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad773a2bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Amphibienlaichgebiete?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Amphibienlaichgebiete?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad773a2970>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Baumkataster?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Baumkataster?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad773a2af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Bebauungsplan?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Bebauungsplan?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7756f310>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Besondere_Waldlebensraeume?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Besondere_Waldlebensraeume?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7748c550>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Bodenkarte?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Bodenkarte?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdbbb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Buslinien?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Buslinien?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdba90>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Denkmaeler?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Denkmaeler?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76825700>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Einzelbaeume_K5?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Einzelbaeume_K5?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdbeb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Erdwaermenutzung?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Erdwaermenutzung?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdba60>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Erholungswald?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Erholungswald?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7748c4c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Fahrzeuglaengen_geplant?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Fahrzeuglaengen_geplant?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7748ca60>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Fledermaus-Quartiere?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Fledermaus-Quartiere?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7756fc10>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Forstreviere?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Forstreviere?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad773a2df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Fussgaengerstreifen?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Fussgaengerstreifen?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad773a2400>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Gebaeudebrueter?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Gebaeudebrueter?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7756f2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Geomorphologie?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Geomorphologie?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7748cdc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Gewaessernetz?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Gewaessernetz?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7748c5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Gewaesserschutzkarte?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Gewaesserschutzkarte?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdb130>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Hecken_Feldgehoelze?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Hecken_Feldgehoelze?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad774e6f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Hist_Gewaesser?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Hist_Gewaesser?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad768259d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Hoehenkurven_Isobathen?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Hoehenkurven_Isobathen?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad773a21c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Jagdbezirke?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=1.1.0
KT_ZG": HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Jagdbezirke?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=1.1.0%0AKT_ZG%22 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdbbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Kunstbauten?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Kunstbauten?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdb460>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Landwertzonen_Steuern?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Landwertzonen_Steuern?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7748c520>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Landwirtschaft?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Landwirtschaft?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7756f040>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Messstellen_an_Gewaessern?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Messstellen_an_Gewaessern?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7756f6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Moorlandschaften?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Moorlandschaften?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad771645b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/NGHK_Phaenomene?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/NGHK_Phaenomene?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7756fb80>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/NGHK_Prozesse?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/NGHK_Prozesse?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7748c880>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Naturobjekte?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Naturobjekte?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7748c820>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Naturschutz?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Naturschutz?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdbb20>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Neophyten?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Neophyten?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdbbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Ortsbildschutz?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Ortsbildschutz?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76825fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Parkplaetze?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Parkplaetze?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad773a2eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Parkplaetze?SERVICE=WMS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Parkplaetze?SERVICE=WMS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdb460>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Points_of_Interest?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Points_of_Interest?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7748c970>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Quartiergestaltungsplanung?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Quartiergestaltungsplanung?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7748c550>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Radwege?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Radwege?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad768257c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Richtplan?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Richtplan?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7756f250>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Schulhaeuser_Kindergaerten?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Schulhaeuser_Kindergaerten?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad77164190>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Schutzraumbau?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Schutzraumbau?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad773a2a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Schutzwald?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Schutzwald?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7756f2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Standorte_Wahlplakate?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Standorte_Wahlplakate?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76825df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Statische_Waldgrenzen?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Statische_Waldgrenzen?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7748c610>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Strassenlaermkataster_Gemeindestrassen?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Strassenlaermkataster_Gemeindestrassen?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdba90>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Strassenlaermkataster_Kantonsstrassen?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Strassenlaermkataster_Kantonsstrassen?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdb4c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Treffpunkte_RDZ?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Treffpunkte_RDZ?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad77164be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Verkehrszaehlung?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Verkehrszaehlung?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdb3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/Zonenplan?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/Zonenplan?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad76bdb4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/defibrillatoren?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/defibrillatoren?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7748c9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/geologisches_aufschlussarchiv?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/geologisches_aufschlussarchiv?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad768250d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/kbs?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/kbs?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7756f2b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/pbv?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/pbv?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad773a21c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/ows/stand_der_erschliessung?SERVICE=WFS&REQUEST=GetCapabilities: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /ows/stand_der_erschliessung?SERVICE=WFS&REQUEST=GetCapabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad77164070>: Failed to establish a new connection: [Errno 111] Connection refused'))
KT_ZG https://services.geo.zg.ch/tc/wmts/1.0.0/WMTSCapabilities.xml: HTTPSConnectionPool(host='services.geo.zg.ch', port=443): Max retries exceeded with url: /tc/wmts/1.0.0/WMTSCapabilities.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad7756f6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
